function Ce_2D = Ce_2D_Primitive(rho)
%CE_2D_PRIMITIVE
%    CE_2D = CE_2D_PRIMITIVE(E,NU,RHO)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Jul-2023 20:22:27
global FE
E = FE.material.E;
nu = FE.material.nu;
%-----------
% rho = 1.875*thick;
t0 = zeros(length(rho),1);
%-----------
t2 = nu.*2.0;
t3 = nu+1.0;
t4 = nu-1.0;
t8 = rho.*1.861895037450197;
t9 = rho.*1.922884335121061;
t5 = t2-1.0;
t6 = 1.0./t3;
t10 = exp(t8);
t11 = exp(t9);
t7 = 1.0./t5;
t12 = t11.*1.662605565779405e-1;
t13 = t10.*1.826775953913206e-1;
t14 = t12-1.662605565779405e-1;
t15 = t13-1.826775953913206e-1;
t16 = E.*nu.*t6.*t7.*t14;
t18 = E.*t4.*t6.*t7.*t15;
t17 = -t16;
Ce_2D = [t18, t17, t0, t17, t18, t0, t0, t0, (E.*t6.*(exp(rho.*1.148464883136739).*4.613222557543144e-1-4.613222557543144e-1))./2.0];
FE.Ce(:,:,:) = reshape(Ce_2D',[3,3,FE.n_elem]);

