function dCe_2D = dCe_2D_Primitive(rho)
%DCE_2D_PRIMITIVE
%    DCE_2D = DCE_2D_PRIMITIVE(E,NU,RHO)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Jul-2023 20:22:27
global FE
E = FE.material.E;
nu = FE.material.nu;
%-----------
% rho = 1.875*thick;
t0 = zeros(length(rho),1);
%-----------
t2 = nu.*2.0;
t3 = nu+1.0;
t4 = nu-1.0;
t8 = rho.*1.861895037450197;
t9 = rho.*1.922884335121061;
t5 = t2-1.0;
t6 = 1.0./t3;
t10 = exp(t8);
t11 = exp(t9);
t7 = 1.0./t5;
t12 = E.*nu.*t6.*t7.*t11.*3.196998197922306e-1;
t14 = E.*t4.*t6.*t7.*t10.*3.401265083124348e-1;
t13 = -t12;
dCe_2D = [t14, t13, t0, t13, t14, t0, t0, t0, E.*t6.*exp(rho.*1.148464883136739).*2.649062052716279e-1];
%----------------------------------------------
FE.dCe(:,:,:) = reshape(dCe_2D',[3,3,FE.n_elem]);
