function dKe_2D = dKe_2D_Primitive(rho)
%DKE_2D_PRIMITIVE
%    DKE_2D = DKE_2D_PRIMITIVE(E,NU,RHO)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Jul-2023 20:22:01
global FE
E = FE.material.E;
nu = FE.material.nu;
%-----------
% rho = 1.875*thick;
t0 = zeros(length(rho),1);
%-----------
t2 = nu.*2.0;
t3 = nu+1.0;
t4 = nu-1.0;
t8 = rho.*1.922884335121061;
t9 = rho.*1.148464883136739;
t10 = rho.*1.861895037450197;
t5 = t2-1.0;
t6 = 1.0./t3;
t11 = exp(t8);
t12 = exp(t9);
t13 = exp(t10);
t7 = 1.0./t5;
t14 = E.*t6.*t12.*4.415103421193795e-2;
t16 = E.*t6.*t12.*6.622655131790693e-2;
t17 = E.*t6.*t12.*8.830206842387591e-2;
t15 = -t14;
t18 = -t16;
t19 = -t17;
t20 = E.*t4.*t6.*t7.*t13.*5.668775138540579e-2;
t21 = E.*nu.*t6.*t7.*t11.*7.992495494805766e-2;
t24 = E.*t4.*t6.*t7.*t13.*1.133755027708116e-1;
t22 = -t20;
t23 = -t21;
t25 = -t24;
t27 = t16+t21;
t29 = t19+t20;
t30 = t18+t21;
t32 = t17+t24;
t26 = t15+t22;
t28 = t14+t25;
t31 = t16+t23;
t33 = t18+t23;
dKe_2D = [t32,t31,t28,t33,t26,t30,t29,t27,t31,t32,t27,t29,t30,t26,t33,t28,t28,t27,t32,t30,t29,t33,t26,t31,t33,t29,t30,t32,t27,t28,t31,t26,t26,t30,t29,t27,t32,t31,t28,t33,t30,t26,t33,t28,t31,t32,t27,t29,t29,t33,t26,t31,t28,t27,t32,t30,t27,t28,t31,t26,t33,t29,t30,t32];
FE.dKe(:,:,:) = reshape(dKe_2D',[8,8,FE.n_elem]);

