function Ke_2D_Primitive(rho)
%KE_2D_PRIMITIVE
%    KE_2D = KE_2D_PRIMITIVE(E,NU,RHO)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Jul-2023 20:22:01
global FE
E = FE.material.E;
nu = FE.material.nu;
%-----------
% rho = 1.875*thick;
t0 = zeros(length(rho),1);
%-----------
t2 = nu.*2.0;
t3 = nu+1.0;
t4 = nu-1.0;
t8 = rho.*1.922884335121061;
t9 = rho.*1.148464883136739;
t10 = rho.*1.861895037450197;
t5 = t2-1.0;
t6 = 1.0./t3;
t11 = exp(t8);
t12 = exp(t9);
t13 = exp(t10);
t7 = 1.0./t5;
t14 = t12.*4.613222557543144e-1;
t15 = t11.*1.662605565779405e-1;
t16 = t13.*1.826775953913206e-1;
t17 = t14-4.613222557543144e-1;
t18 = t16-1.826775953913206e-1;
t19 = t15-1.662605565779405e-1;
t20 = E.*t6.*t17.*8.333333333333332e-2;
t22 = E.*t6.*t17.*1.25e-1;
t23 = E.*t6.*t17.*1.666666666666667e-1;
t26 = E.*nu.*t6.*t7.*t19.*2.5e-1;
t28 = E.*t4.*t6.*t7.*t18.*1.666666666666666e-1;
t30 = E.*t4.*t6.*t7.*t18.*3.333333333333333e-1;
t21 = -t20;
t24 = -t22;
t25 = -t23;
t27 = -t26;
t29 = -t28;
t31 = -t30;
t32 = t22+t26;
t39 = t23+t30;
t33 = t24+t26;
t34 = t22+t27;
t35 = t21+t29;
t36 = t20+t31;
t37 = t25+t28;
t38 = t24+t27;
Ke_2D = [t39,t34,t36,t38,t35,t33,t37,t32,t34,t39,t32,t37,t33,t35,t38,t36,t36,t32,t39,t33,t37,t38,t35,t34,t38,t37,t33,t39,t32,t36,t34,t35,t35,t33,t37,t32,t39,t34,t36,t38,t33,t35,t38,t36,t34,t39,t32,t37,t37,t38,t35,t34,t36,t32,t39,t33,t32,t36,t34,t35,t38,t37,t33,t39];
FE.Ke(:,:,:) = reshape(Ke_2D',[8,8,FE.n_elem]);