function Ce_2D = Ce_2D_Primitive(E,nu,thick)
%CE_2D_PRIMITIVE
%    CE_2D = CE_2D_PRIMITIVE(E,NU,THICK)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Jul-2023 14:44:41

t2 = nu.*2.0;
t3 = nu+1.0;
t4 = nu-1.0;
t8 = thick.*3.491053195219119;
t9 = thick.*3.60540812835199;
t5 = t2-1.0;
t6 = 1.0./t3;
t10 = exp(t8);
t11 = exp(t9);
t7 = 1.0./t5;
t12 = t11.*1.662605565779405e-1;
t13 = t10.*1.826775953913206e-1;
t14 = t12-1.662605565779405e-1;
t15 = t13-1.826775953913206e-1;
t16 = E.*nu.*t6.*t7.*t14;
t18 = E.*t4.*t6.*t7.*t15;
t17 = -t16;
Ce_2D = reshape([t18,t17,0.0,t17,t18,0.0,0.0,0.0,(E.*t6.*(exp(thick.*2.153371655881386).*4.613222557543144e-1-4.613222557543144e-1))./2.0],[3,3]);
