function dKe_2D = dKe_2D_Primitive(E,nu,thick)
%DKE_2D_PRIMITIVE
%    DKE_2D = DKE_2D_PRIMITIVE(E,NU,THICK)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Jul-2023 14:46:26

t2 = nu.*2.0;
t3 = nu+1.0;
t4 = nu-1.0;
t8 = thick.*3.491053195219119;
t9 = thick.*2.153371655881386;
t10 = thick.*3.60540812835199;
t5 = t2-1.0;
t6 = 1.0./t3;
t11 = exp(t9);
t12 = exp(t10);
t13 = exp(t8);
t7 = 1.0./t5;
t14 = E.*t6.*t11.*8.278318914738367e-2;
t16 = E.*t6.*t11.*1.655663782947674e-1;
t17 = E.*t6.*t11.*1.241747837210755e-1;
t15 = -t14;
t18 = -t16;
t19 = -t17;
t20 = E.*t4.*t6.*t7.*t13.*1.062895338476359e-1;
t22 = E.*nu.*t6.*t7.*t12.*1.498592905276081e-1;
t23 = E.*t4.*t6.*t7.*t13.*2.125790676952717e-1;
t21 = -t20;
t24 = -t22;
t25 = -t23;
t27 = t17+t22;
t29 = t18+t20;
t30 = t19+t22;
t32 = t16+t23;
t26 = t15+t21;
t28 = t14+t25;
t31 = t17+t24;
t33 = t19+t24;
dKe_2D = reshape([t32,t31,t28,t33,t26,t30,t29,t27,t31,t32,t27,t29,t30,t26,t33,t28,t28,t27,t32,t30,t29,t33,t26,t31,t33,t29,t30,t32,t27,t28,t31,t26,t26,t30,t29,t27,t32,t31,t28,t33,t30,t26,t33,t28,t31,t32,t27,t29,t29,t33,t26,t31,t28,t27,t32,t30,t27,t28,t31,t26,t33,t29,t30,t32],[8,8]);
